name: Linting and Testing
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: node_modules
          key: v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            v1-
      - name: Install dependencies with yarn
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install
  lint-and-test:
    runs-on: ubuntu-latest
    needs: build
    env:
      NODE_ENV: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: node_modules
          key: v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            v1-
      - name: Run Linter
        if: steps.yarn-cache.outputs.cache-hit == 'true'
        run: yarn lint
      - name: Run Server Tests
        if: steps.yarn-cache.outputs.cache-hit == 'true'
        run: yarn test:server
      - name: Run UI Tests
        if: steps.yarn-cache.outputs.cache-hit == 'true'
        run: yarn test:client
